/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as ContactImport } from './routes/contact'
import { Route as BlogImport } from './routes/blog'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as BookAssessmentImport } from './routes/book-assessment'
import { Route as BlogArticleIdImport } from './routes/blog.$articleId'
import { Route as ServiceBimImport } from './routes/service-bim'
import { Route as ServiceRdsImport } from './routes/service-rds'
import { Route as ServiceRdsAuditImport } from './routes/service-rds-audit'
import { Route as ServiceProjectManagementImport } from './routes/service-project-management'
import { Route as ServiceDocumentManagementImport } from './routes/service-document-management'
import { Route as ServiceProductDevelopmentImport } from './routes/service-product-development'
import { Route as ServiceTrainingImport } from './routes/service-training'
import { Route as ServiceRdsPsImport } from './routes/service-rds-ps'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BookAssessmentRoute = BookAssessmentImport.update({
  id: '/book-assessment',
  path: '/book-assessment',
  getParentRoute: () => rootRoute,
} as any)

const BlogArticleIdRoute = BlogArticleIdImport.update({
  id: '/blog/$articleId',
  path: '/blog/$articleId',
  getParentRoute: () => rootRoute,
} as any)

const ServiceBimRoute = ServiceBimImport.update({
  id: '/service-bim',
  path: '/service-bim',
  getParentRoute: () => rootRoute,
} as any)

const ServiceRdsRoute = ServiceRdsImport.update({
  id: '/service-rds',
  path: '/service-rds',
  getParentRoute: () => rootRoute,
} as any)

const ServiceRdsAuditRoute = ServiceRdsAuditImport.update({
  id: '/service-rds-audit',
  path: '/service-rds-audit',
  getParentRoute: () => rootRoute,
} as any)

const ServiceProjectManagementRoute = ServiceProjectManagementImport.update({
  id: '/service-project-management',
  path: '/service-project-management',
  getParentRoute: () => rootRoute,
} as any)

const ServiceDocumentManagementRoute = ServiceDocumentManagementImport.update({
  id: '/service-document-management',
  path: '/service-document-management',
  getParentRoute: () => rootRoute,
} as any)

const ServiceProductDevelopmentRoute = ServiceProductDevelopmentImport.update({
  id: '/service-product-development',
  path: '/service-product-development',
  getParentRoute: () => rootRoute,
} as any)

const ServiceRdsPsRoute = ServiceRdsPsImport.update({
  id: '/service-rds-ps',
  path: '/service-rds-ps',
  getParentRoute: () => rootRoute,
} as any)

const ServiceTrainingRoute = ServiceTrainingImport.update({
  id: '/service-training',
  path: '/service-training',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/book-assessment': {
      id: '/book-assessment'
      path: '/book-assessment'
      fullPath: '/book-assessment'
      preLoaderRoute: typeof BookAssessmentImport
      parentRoute: typeof rootRoute
    }
    '/blog/$articleId': {
      id: '/blog/$articleId'
      path: '/blog/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdImport
      parentRoute: typeof rootRoute
    }
    '/service-bim': {
      id: '/service-bim'
      path: '/service-bim'
      fullPath: '/service-bim'
      preLoaderRoute: typeof ServiceBimImport
      parentRoute: typeof rootRoute
    }
    '/service-rds': {
      id: '/service-rds'
      path: '/service-rds'
      fullPath: '/service-rds'
      preLoaderRoute: typeof ServiceRdsImport
      parentRoute: typeof rootRoute
    }
    '/service-rds-audit': {
      id: '/service-rds-audit'
      path: '/service-rds-audit'
      fullPath: '/service-rds-audit'
      preLoaderRoute: typeof ServiceRdsAuditImport
      parentRoute: typeof rootRoute
    }
    '/service-project-management': {
      id: '/service-project-management'
      path: '/service-project-management'
      fullPath: '/service-project-management'
      preLoaderRoute: typeof ServiceProjectManagementImport
      parentRoute: typeof rootRoute
    }
    '/service-document-management': {
      id: '/service-document-management'
      path: '/service-document-management'
      fullPath: '/service-document-management'
      preLoaderRoute: typeof ServiceDocumentManagementImport
      parentRoute: typeof rootRoute
    }
    '/service-product-development': {
      id: '/service-product-development'
      path: '/service-product-development'
      fullPath: '/service-product-development'
      preLoaderRoute: typeof ServiceProductDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/service-rds-ps': {
      id: '/service-rds-ps'
      path: '/service-rds-ps'
      fullPath: '/service-rds-ps'
      preLoaderRoute: typeof ServiceRdsPsImport
      parentRoute: typeof rootRoute
    }
    '/service-training': {
      id: '/service-training'
      path: '/service-training'
      fullPath: '/service-training'
      preLoaderRoute: typeof ServiceTrainingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/service-bim': typeof ServiceBimRoute
  '/service-rds': typeof ServiceRdsRoute
  '/service-rds-audit': typeof ServiceRdsAuditRoute
  '/service-project-management': typeof ServiceProjectManagementRoute
  '/service-document-management': typeof ServiceDocumentManagementRoute
  '/service-product-development': typeof ServiceProductDevelopmentRoute
  '/service-rds-ps': typeof ServiceRdsPsRoute
  '/service-training': typeof ServiceTrainingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/service-bim': typeof ServiceBimRoute
  '/service-rds': typeof ServiceRdsRoute
  '/service-rds-audit': typeof ServiceRdsAuditRoute
  '/service-project-management': typeof ServiceProjectManagementRoute
  '/service-document-management': typeof ServiceDocumentManagementRoute
  '/service-product-development': typeof ServiceProductDevelopmentRoute
  '/service-rds-ps': typeof ServiceRdsPsRoute
  '/service-rds-ps': typeof ServiceRdsPsRoute
  '/service-training': typeof ServiceTrainingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/service-bim': typeof ServiceBimRoute
  '/service-rds': typeof ServiceRdsRoute
  '/service-rds-audit': typeof ServiceRdsAuditRoute
  '/service-project-management': typeof ServiceProjectManagementRoute
  '/service-document-management': typeof ServiceDocumentManagementRoute
  '/service-product-development': typeof ServiceProductDevelopmentRoute
  '/service-rds-ps': typeof ServiceRdsPsRoute
  '/service-rds-ps': typeof ServiceRdsPsRoute
  '/service-training': typeof ServiceTrainingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/book-assessment'
    | '/blog/$articleId'
    | '/service-bim'
    | '/service-rds'
    | '/service-rds-audit'
    | '/service-project-management'
    | '/service-document-management'
    | '/service-product-development'
    | '/service-rds-ps'
    | '/service-rds-ps'
    | '/service-training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/book-assessment'
    | '/blog/$articleId'
    | '/service-bim'
    | '/service-rds'
    | '/service-rds-audit'
    | '/service-project-management'
    | '/service-document-management'
    | '/service-product-development'
    | '/service-rds-ps'
    | '/service-training'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/book-assessment'
    | '/blog/$articleId'
    | '/service-bim'
    | '/service-rds'
    | '/service-rds-audit'
    | '/service-project-management'
    | '/service-document-management'
    | '/service-product-development'
    | '/service-rds-ps'
    | '/service-rds-ps'
    | '/service-training'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  BookAssessmentRoute: typeof BookAssessmentRoute
  BlogArticleIdRoute: typeof BlogArticleIdRoute
  ServiceBimRoute: typeof ServiceBimRoute
  ServiceRdsRoute: typeof ServiceRdsRoute
  ServiceRdsAuditRoute: typeof ServiceRdsAuditRoute
  ServiceProjectManagementRoute: typeof ServiceProjectManagementRoute
  ServiceDocumentManagementRoute: typeof ServiceDocumentManagementRoute
  ServiceProductDevelopmentRoute: typeof ServiceProductDevelopmentRoute
  ServiceRdsPsRoute: typeof ServiceRdsPsRoute
  ServiceTrainingRoute: typeof ServiceTrainingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  BookAssessmentRoute: BookAssessmentRoute,
  BlogArticleIdRoute: BlogArticleIdRoute,
  ServiceBimRoute: ServiceBimRoute,
  ServiceRdsRoute: ServiceRdsRoute,
  ServiceRdsAuditRoute: ServiceRdsAuditRoute,
  ServiceProjectManagementRoute: ServiceProjectManagementRoute,
  ServiceDocumentManagementRoute: ServiceDocumentManagementRoute,
  ServiceProductDevelopmentRoute: ServiceProductDevelopmentRoute,
  ServiceRdsPsRoute: ServiceRdsPsRoute,
  ServiceTrainingRoute: ServiceTrainingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
